// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD6WoyX3oJawiTv9v4RlzWo41vfglGDJ78',
    appId: '1:246713456730:web:6a59c7b3540269c59a2063',
    messagingSenderId: '246713456730',
    projectId: 'dailyhunt-30290',
    authDomain: 'dailyhunt-30290.firebaseapp.com',
    storageBucket: 'dailyhunt-30290.firebasestorage.app',
    measurementId: 'G-9D8XQ5CHFY',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBpVLoaXlXO4fMcQFCIj26smZp49IPpVow',
    appId: '1:246713456730:android:b351717556972c1b9a2063',
    messagingSenderId: '246713456730',
    projectId: 'dailyhunt-30290',
    storageBucket: 'dailyhunt-30290.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC3h-txpAwyBWlh3lL4GniRTZvx1o_Wu80',
    appId: '1:246713456730:ios:6ec6f2669e6d55b59a2063',
    messagingSenderId: '246713456730',
    projectId: 'dailyhunt-30290',
    storageBucket: 'dailyhunt-30290.firebasestorage.app',
    iosBundleId: 'com.example.dailyhunt',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyC3h-txpAwyBWlh3lL4GniRTZvx1o_Wu80',
    appId: '1:246713456730:ios:6ec6f2669e6d55b59a2063',
    messagingSenderId: '246713456730',
    projectId: 'dailyhunt-30290',
    storageBucket: 'dailyhunt-30290.firebasestorage.app',
    iosBundleId: 'com.example.dailyhunt',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyD6WoyX3oJawiTv9v4RlzWo41vfglGDJ78',
    appId: '1:246713456730:web:a3ad77511cf84ee99a2063',
    messagingSenderId: '246713456730',
    projectId: 'dailyhunt-30290',
    authDomain: 'dailyhunt-30290.firebaseapp.com',
    storageBucket: 'dailyhunt-30290.firebasestorage.app',
    measurementId: 'G-PVM9HHRJLZ',
  );

}